// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_CLONE_PDFDOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_CLONE_PDFDOCUMENT
void*_Nonnull uniffi_pdfree_ffi_fn_clone_pdfdocument(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FREE_PDFDOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FREE_PDFDOCUMENT
void uniffi_pdfree_ffi_fn_free_pdfdocument(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_CONSTRUCTOR_PDFDOCUMENT_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_CONSTRUCTOR_PDFDOCUMENT_FROM_BYTES
void*_Nonnull uniffi_pdfree_ffi_fn_constructor_pdfdocument_from_bytes(RustBuffer data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_AUTHOR
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_author(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_CREATOR
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_creator(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PAGE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PAGE_COUNT
uint16_t uniffi_pdfree_ffi_fn_method_pdfdocument_page_count(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PAGE_SIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PAGE_SIZE
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_page_size(void*_Nonnull ptr, uint16_t index, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PRODUCER
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_PRODUCER
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_producer(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_RENDER_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_RENDER_PAGE
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_render_page(void*_Nonnull ptr, uint16_t index, uint32_t dpi, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_SUBJECT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_SUBJECT
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_subject(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_TITLE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_METHOD_PDFDOCUMENT_TITLE
RustBuffer uniffi_pdfree_ffi_fn_method_pdfdocument_title(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_ADD_ANNOTATIONS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_ADD_ANNOTATIONS
RustBuffer uniffi_pdfree_ffi_fn_func_add_annotations(RustBuffer pdf_bytes, RustBuffer annotations, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_CLASSIFY
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_CLASSIFY
RustBuffer uniffi_pdfree_ffi_fn_func_ai_classify(RustBuffer pdf_bytes, RustBuffer provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_DETECT_PII
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_DETECT_PII
RustBuffer uniffi_pdfree_ffi_fn_func_ai_detect_pii(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_EXTRACT_TABLES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_EXTRACT_TABLES
RustBuffer uniffi_pdfree_ffi_fn_func_ai_extract_tables(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_OCR_RECOGNIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_OCR_RECOGNIZE
RustBuffer uniffi_pdfree_ffi_fn_func_ai_ocr_recognize(RustBuffer page_png, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_RAG_ANSWER
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_RAG_ANSWER
RustBuffer uniffi_pdfree_ffi_fn_func_ai_rag_answer(RustBuffer pdf_bytes, RustBuffer question, RustBuffer provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_REDACT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_REDACT
RustBuffer uniffi_pdfree_ffi_fn_func_ai_redact(RustBuffer pdf_bytes, RustBuffer spans, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_SUGGEST_FORM_FILLS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_SUGGEST_FORM_FILLS
RustBuffer uniffi_pdfree_ffi_fn_func_ai_suggest_form_fills(RustBuffer pdf_bytes, RustBuffer profile, RustBuffer provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_AI_SUMMARIZE
RustBuffer uniffi_pdfree_ffi_fn_func_ai_summarize(RustBuffer pdf_bytes, RustBuffer provider, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_BOX_AT_POINT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_BOX_AT_POINT
RustBuffer uniffi_pdfree_ffi_fn_func_box_at_point(RustBuffer pdf_bytes, uint16_t page, float x, float y, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_BOXES_ON_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_BOXES_ON_PAGE
RustBuffer uniffi_pdfree_ffi_fn_func_boxes_on_page(RustBuffer pdf_bytes, uint16_t page, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_EXTRACT_PAGES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_EXTRACT_PAGES
RustBuffer uniffi_pdfree_ffi_fn_func_extract_pages(RustBuffer pdf_bytes, RustBuffer pages, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FIT_TO_PAGE_DPI
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FIT_TO_PAGE_DPI
float uniffi_pdfree_ffi_fn_func_fit_to_page_dpi(float page_width_pts, float page_height_pts, float viewport_width_px, float viewport_height_px, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FORM_FIELDS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FORM_FIELDS
RustBuffer uniffi_pdfree_ffi_fn_func_form_fields(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FORM_FILL
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FORM_FILL
RustBuffer uniffi_pdfree_ffi_fn_func_form_fill(RustBuffer pdf_bytes, RustBuffer values, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FROM_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_FROM_IMAGE
RustBuffer uniffi_pdfree_ffi_fn_func_from_image(RustBuffer image_bytes, float dpi, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_LIST_ANNOTATIONS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_LIST_ANNOTATIONS
RustBuffer uniffi_pdfree_ffi_fn_func_list_annotations(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_MERGE_DOCUMENTS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_MERGE_DOCUMENTS
RustBuffer uniffi_pdfree_ffi_fn_func_merge_documents(RustBuffer documents, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_OVERLAY_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_OVERLAY_TEXT
RustBuffer uniffi_pdfree_ffi_fn_func_overlay_text(RustBuffer pdf_bytes, RustBuffer overlays, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_PLACE_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_PLACE_SIGNATURE
RustBuffer uniffi_pdfree_ffi_fn_func_place_signature(RustBuffer pdf_bytes, RustBuffer image_png, RustBuffer at, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_PLACE_SIGNATURE_WITH_AUDIT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_PLACE_SIGNATURE_WITH_AUDIT
RustBuffer uniffi_pdfree_ffi_fn_func_place_signature_with_audit(RustBuffer pdf_bytes, RustBuffer image_png, RustBuffer at, RustBuffer audit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_REORDER_PAGES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_REORDER_PAGES
RustBuffer uniffi_pdfree_ffi_fn_func_reorder_pages(RustBuffer pdf_bytes, RustBuffer new_order, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_REPLACE_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_REPLACE_TEXT
RustBuffer uniffi_pdfree_ffi_fn_func_replace_text(RustBuffer pdf_bytes, uint16_t page, RustBuffer find, RustBuffer replace, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_ROTATE_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_ROTATE_PAGE
RustBuffer uniffi_pdfree_ffi_fn_func_rotate_page(RustBuffer pdf_bytes, uint16_t page, RustBuffer rotation, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_SPLIT_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_SPLIT_DOCUMENT
RustBuffer uniffi_pdfree_ffi_fn_func_split_document(RustBuffer pdf_bytes, RustBuffer ranges, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TEXT_RUN_AT_POINT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TEXT_RUN_AT_POINT
RustBuffer uniffi_pdfree_ffi_fn_func_text_run_at_point(RustBuffer pdf_bytes, uint16_t page, float x, float y, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TEXT_RUNS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TEXT_RUNS
RustBuffer uniffi_pdfree_ffi_fn_func_text_runs(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TO_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_TO_TEXT
RustBuffer uniffi_pdfree_ffi_fn_func_to_text(RustBuffer pdf_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_VERSION
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_FN_FUNC_VERSION
RustBuffer uniffi_pdfree_ffi_fn_func_version(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_pdfree_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_pdfree_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_FREE
void ffi_pdfree_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_pdfree_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U8
void ffi_pdfree_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U8
void ffi_pdfree_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U8
void ffi_pdfree_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_pdfree_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I8
void ffi_pdfree_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I8
void ffi_pdfree_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I8
void ffi_pdfree_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_pdfree_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U16
void ffi_pdfree_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U16
void ffi_pdfree_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U16
void ffi_pdfree_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_pdfree_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I16
void ffi_pdfree_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I16
void ffi_pdfree_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I16
void ffi_pdfree_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_pdfree_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U32
void ffi_pdfree_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U32
void ffi_pdfree_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U32
void ffi_pdfree_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_pdfree_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I32
void ffi_pdfree_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I32
void ffi_pdfree_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I32
void ffi_pdfree_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_pdfree_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_U64
void ffi_pdfree_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_U64
void ffi_pdfree_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_U64
void ffi_pdfree_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_pdfree_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_I64
void ffi_pdfree_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_I64
void ffi_pdfree_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_I64
void ffi_pdfree_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_pdfree_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_F32
void ffi_pdfree_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_F32
void ffi_pdfree_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_F32
void ffi_pdfree_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_pdfree_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_F64
void ffi_pdfree_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_F64
void ffi_pdfree_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_F64
void ffi_pdfree_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_pdfree_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_POINTER
void ffi_pdfree_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_pdfree_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_POINTER
void ffi_pdfree_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_pdfree_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_pdfree_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_pdfree_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_pdfree_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_pdfree_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_POLL_VOID
void ffi_pdfree_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_pdfree_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_FREE_VOID
void ffi_pdfree_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_pdfree_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_ADD_ANNOTATIONS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_ADD_ANNOTATIONS
uint16_t uniffi_pdfree_ffi_checksum_func_add_annotations(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_CLASSIFY
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_CLASSIFY
uint16_t uniffi_pdfree_ffi_checksum_func_ai_classify(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_DETECT_PII
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_DETECT_PII
uint16_t uniffi_pdfree_ffi_checksum_func_ai_detect_pii(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_EXTRACT_TABLES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_EXTRACT_TABLES
uint16_t uniffi_pdfree_ffi_checksum_func_ai_extract_tables(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_OCR_RECOGNIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_OCR_RECOGNIZE
uint16_t uniffi_pdfree_ffi_checksum_func_ai_ocr_recognize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_RAG_ANSWER
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_RAG_ANSWER
uint16_t uniffi_pdfree_ffi_checksum_func_ai_rag_answer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_REDACT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_REDACT
uint16_t uniffi_pdfree_ffi_checksum_func_ai_redact(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_SUGGEST_FORM_FILLS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_SUGGEST_FORM_FILLS
uint16_t uniffi_pdfree_ffi_checksum_func_ai_suggest_form_fills(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_SUMMARIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_AI_SUMMARIZE
uint16_t uniffi_pdfree_ffi_checksum_func_ai_summarize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_BOX_AT_POINT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_BOX_AT_POINT
uint16_t uniffi_pdfree_ffi_checksum_func_box_at_point(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_BOXES_ON_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_BOXES_ON_PAGE
uint16_t uniffi_pdfree_ffi_checksum_func_boxes_on_page(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_EXTRACT_PAGES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_EXTRACT_PAGES
uint16_t uniffi_pdfree_ffi_checksum_func_extract_pages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FIT_TO_PAGE_DPI
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FIT_TO_PAGE_DPI
uint16_t uniffi_pdfree_ffi_checksum_func_fit_to_page_dpi(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FORM_FIELDS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FORM_FIELDS
uint16_t uniffi_pdfree_ffi_checksum_func_form_fields(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FORM_FILL
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FORM_FILL
uint16_t uniffi_pdfree_ffi_checksum_func_form_fill(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FROM_IMAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_FROM_IMAGE
uint16_t uniffi_pdfree_ffi_checksum_func_from_image(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_LIST_ANNOTATIONS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_LIST_ANNOTATIONS
uint16_t uniffi_pdfree_ffi_checksum_func_list_annotations(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_MERGE_DOCUMENTS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_MERGE_DOCUMENTS
uint16_t uniffi_pdfree_ffi_checksum_func_merge_documents(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_OVERLAY_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_OVERLAY_TEXT
uint16_t uniffi_pdfree_ffi_checksum_func_overlay_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_PLACE_SIGNATURE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_PLACE_SIGNATURE
uint16_t uniffi_pdfree_ffi_checksum_func_place_signature(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_PLACE_SIGNATURE_WITH_AUDIT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_PLACE_SIGNATURE_WITH_AUDIT
uint16_t uniffi_pdfree_ffi_checksum_func_place_signature_with_audit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_REORDER_PAGES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_REORDER_PAGES
uint16_t uniffi_pdfree_ffi_checksum_func_reorder_pages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_REPLACE_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_REPLACE_TEXT
uint16_t uniffi_pdfree_ffi_checksum_func_replace_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_ROTATE_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_ROTATE_PAGE
uint16_t uniffi_pdfree_ffi_checksum_func_rotate_page(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_SPLIT_DOCUMENT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_SPLIT_DOCUMENT
uint16_t uniffi_pdfree_ffi_checksum_func_split_document(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TEXT_RUN_AT_POINT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TEXT_RUN_AT_POINT
uint16_t uniffi_pdfree_ffi_checksum_func_text_run_at_point(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TEXT_RUNS
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TEXT_RUNS
uint16_t uniffi_pdfree_ffi_checksum_func_text_runs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TO_TEXT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_TO_TEXT
uint16_t uniffi_pdfree_ffi_checksum_func_to_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_VERSION
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_FUNC_VERSION
uint16_t uniffi_pdfree_ffi_checksum_func_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_AUTHOR
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_AUTHOR
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_author(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_CREATOR
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_CREATOR
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_creator(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PAGE_COUNT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PAGE_COUNT
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_page_count(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PAGE_SIZE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PAGE_SIZE
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_page_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PRODUCER
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_PRODUCER
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_producer(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_RENDER_PAGE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_RENDER_PAGE
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_render_page(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_SUBJECT
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_SUBJECT
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_subject(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_TITLE
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_METHOD_PDFDOCUMENT_TITLE
uint16_t uniffi_pdfree_ffi_checksum_method_pdfdocument_title(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_CONSTRUCTOR_PDFDOCUMENT_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_PDFREE_FFI_CHECKSUM_CONSTRUCTOR_PDFDOCUMENT_FROM_BYTES
uint16_t uniffi_pdfree_ffi_checksum_constructor_pdfdocument_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_PDFREE_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_PDFREE_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_pdfree_ffi_uniffi_contract_version(void
    
);
#endif

