#!/usr/bin/env bash
# Build the WASM bindings for the web app: compile pdfree-wasm for
# wasm32-unknown-unknown, then run it through the wasm-bindgen CLI to emit
# an ES module (`--target web`) + .d.ts into apps/web/src/wasm/ (gitignored,
# regenerated by this script — see apps/macos/Sources/Bridge/ for the same
# pattern on the Swift side).
#
# Requires:
#   - A rustup-managed toolchain with the wasm32-unknown-unknown target.
#     This repo's other crates build fine with a plain Homebrew/system Rust
#     install (no rustup), but Homebrew's rustc ships only its own host
#     target — cross-compiling to wasm32 needs rustup's target management:
#       brew install rustup
#       rustup toolchain install stable --profile minimal
#       rustup target add wasm32-unknown-unknown
#   - wasm-bindgen-cli, matching the `wasm-bindgen` crate version in
#     Cargo.lock exactly (a mismatch fails at runtime, not build time):
#       cargo install wasm-bindgen-cli --version <version> --locked
#
# PDFium's actual WASM binary is a separate, larger piece of setup — see
# docs/pdfium-bundling.md's Web section. This script only builds the Rust
# glue; it does not fetch or require the PDFium WASM module itself.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

RUSTUP_TOOLCHAIN_BIN="${RUSTUP_TOOLCHAIN_BIN:-$HOME/.rustup/toolchains/stable-aarch64-apple-darwin/bin}"
if [ ! -x "$RUSTUP_TOOLCHAIN_BIN/cargo" ]; then
  echo "error: rustup-managed cargo not found at $RUSTUP_TOOLCHAIN_BIN" >&2
  echo "  install with: brew install rustup && rustup toolchain install stable --profile minimal && rustup target add wasm32-unknown-unknown" >&2
  exit 1
fi
if ! command -v wasm-bindgen >/dev/null 2>&1; then
  echo "error: wasm-bindgen CLI not found on PATH" >&2
  echo "  install the version matching Cargo.lock's wasm-bindgen entry, e.g.:" >&2
  echo "  cargo install wasm-bindgen-cli --version \$(grep -A1 '^name = \"wasm-bindgen\"' Cargo.lock | grep version | head -1 | cut -d'\"' -f2) --locked" >&2
  exit 1
fi

# PATH order matters here: cargo resolves the rustc it invokes for build
# scripts/proc-macros via PATH, not via its own binary location, so the
# rustup toolchain's bin dir must come first even though we call cargo by
# absolute path.
PATH="$RUSTUP_TOOLCHAIN_BIN:$PATH" "$RUSTUP_TOOLCHAIN_BIN/cargo" build \
  --release -p pdfree-wasm --target wasm32-unknown-unknown

mkdir -p apps/web/src/wasm
wasm-bindgen \
  target/wasm32-unknown-unknown/release/pdfree_wasm.wasm \
  --target web \
  --out-dir apps/web/src/wasm \
  --out-name pdfree_wasm
echo "Generated WASM bindings in apps/web/src/wasm/"
