//! Smart form fill: map a user profile onto a document's detected fields via
//! an LLM (Phase 5).
//!
//! Field names in real-world PDFs are often cryptic (e.g.
//! `topmostSubform[0].Page1[0].f1_01[0]`), so exact-key matching a profile
//! against them isn't reliable. Instead the model is given the full list of
//! field names/kinds plus the user's profile and asked to propose a
//! mapping — the result is a *suggestion* list, not an in-place write, so a
//! wrong guess is caught in a review UI before it ever reaches
//! `pdfree_core::forms::fill`.

use crate::provider::Provider;
use crate::{AiError, Result};
use pdfree_core::forms::{FieldKind, FormField, SignatureFieldKind};
use std::collections::{HashMap, HashSet};

/// A single field the model matched to a profile value, ready to hand to
/// `pdfree_core::forms::fill`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SuggestedFill {
    pub field_name: String,
    pub value: String,
}

/// Ask `provider` to map `profile` onto `fields`, returning only the fields
/// it found a confident match for.
///
/// Signature/initials fields are always excluded from consideration — Core
/// UX Principle #3 (see CLAUDE.md) routes those to the sign flow, never a
/// plain text fill. Dropdown/list-box/radio fields are excluded too: even
/// if the model picked a value, `pdfree_core::forms::fill` has no setter for
/// them yet (see `forms.rs`'s `FillValue` docs), so suggesting one would be
/// a promise this layer can't keep.
pub fn suggest_fills(
    fields: &[FormField],
    profile: &HashMap<String, String>,
    provider: &dyn Provider,
) -> Result<Vec<SuggestedFill>> {
    let fillable: Vec<&FormField> = fields
        .iter()
        .filter(|f| {
            matches!(f.kind, FieldKind::Text | FieldKind::Checkbox)
                && f.signature_kind == SignatureFieldKind::None
        })
        .collect();

    if fillable.is_empty() || profile.is_empty() {
        return Ok(Vec::new());
    }

    let field_list = fillable
        .iter()
        .map(|f| format!("- \"{}\" ({:?})", f.name, f.kind))
        .collect::<Vec<_>>()
        .join("\n");

    let profile_list = profile
        .iter()
        .map(|(key, value)| format!("- {key}: {value}"))
        .collect::<Vec<_>>()
        .join("\n");

    let prompt = format!(
        "You are matching a user's profile data to PDF form fields by field \
         name. Field names are sometimes cryptic (auto-generated by the PDF \
         author's software) — use your best judgment about what each field \
         is likely for based on its name.\n\n\
         Form fields:\n{field_list}\n\n\
         User profile:\n{profile_list}\n\n\
         Respond with ONLY a JSON object mapping each field name you're \
         confident about to the profile value that should fill it. Omit any \
         field you aren't reasonably confident about — do not guess. For \
         checkbox fields, use the string \"true\" or \"false\" as the value. \
         Respond with JSON only, no other text. Example: \
         {{\"FullName\": \"Jane Doe\", \"AgreeToTerms\": \"true\"}}"
    );

    let response = provider.complete(&prompt)?;
    parse_fill_mapping(&response, &fillable)
}

fn parse_fill_mapping(response: &str, fillable: &[&FormField]) -> Result<Vec<SuggestedFill>> {
    let json_str = crate::json_util::extract_json_object(response).ok_or_else(|| {
        AiError::Provider(format!("model response had no JSON object: {response}"))
    })?;

    let parsed: serde_json::Value = serde_json::from_str(json_str)
        .map_err(|e| AiError::Provider(format!("failed to parse form-fill mapping: {e}")))?;

    let map = parsed
        .as_object()
        .ok_or_else(|| AiError::Provider("form-fill mapping was not a JSON object".to_string()))?;

    // Never write to a field we didn't actually detect, no matter what the
    // model proposes — a hallucinated field name is silently dropped.
    let known_names: HashSet<&str> = fillable.iter().map(|f| f.name.as_str()).collect();

    let mut out = Vec::new();
    for (field_name, value) in map {
        if !known_names.contains(field_name.as_str()) {
            continue;
        }
        if let Some(value) = value.as_str().filter(|v| !v.is_empty()) {
            out.push(SuggestedFill {
                field_name: field_name.clone(),
                value: value.to_string(),
            });
        }
    }
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::provider::{OllamaProvider, Provider, Residency};

    struct FixedProvider {
        response: String,
    }

    impl Provider for FixedProvider {
        fn name(&self) -> &str {
            "fixed-test-provider"
        }
        fn residency(&self) -> Residency {
            Residency::Local
        }
        fn complete(&self, _prompt: &str) -> crate::Result<String> {
            Ok(self.response.clone())
        }
    }

    fn text_field(name: &str) -> FormField {
        FormField {
            name: name.to_string(),
            kind: FieldKind::Text,
            value: None,
            page: 0,
            x: 0.0,
            y: 0.0,
            width: 100.0,
            height: 20.0,
            signature_kind: SignatureFieldKind::None,
            radio_group_index: None,
        }
    }

    fn signature_field(name: &str) -> FormField {
        FormField {
            signature_kind: SignatureFieldKind::Signature,
            ..text_field(name)
        }
    }

    // extract_json_object's own tests live in json_util.rs, its new home.

    #[test]
    fn empty_profile_returns_no_suggestions_without_calling_the_model() {
        let fields = vec![text_field("FullName")];
        let profile = HashMap::new();
        let provider = FixedProvider {
            response: "this should never be read".to_string(),
        };
        let result = suggest_fills(&fields, &profile, &provider).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn signature_fields_are_excluded_from_the_candidate_list() {
        let fields = vec![signature_field("Signature1")];
        let mut profile = HashMap::new();
        profile.insert("full_name".to_string(), "Jane Doe".to_string());
        let provider = FixedProvider {
            response: "this should never be read".to_string(),
        };
        // No fillable candidates means suggest_fills short-circuits before
        // ever calling the model.
        let result = suggest_fills(&fields, &profile, &provider).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn suggestions_are_filtered_to_known_field_names() {
        let fields = vec![text_field("FullName")];
        let mut profile = HashMap::new();
        profile.insert("full_name".to_string(), "Jane Doe".to_string());
        let provider = FixedProvider {
            // The model hallucinates a field ("Address1") that isn't in the
            // document — it must be silently dropped, not written.
            response: r#"{"FullName": "Jane Doe", "Address1": "123 Main St"}"#.to_string(),
        };
        let result = suggest_fills(&fields, &profile, &provider).unwrap();
        assert_eq!(
            result,
            vec![SuggestedFill {
                field_name: "FullName".to_string(),
                value: "Jane Doe".to_string(),
            }]
        );
    }

    #[test]
    fn empty_string_values_are_dropped() {
        let fields = vec![text_field("FullName")];
        let mut profile = HashMap::new();
        profile.insert("full_name".to_string(), "Jane Doe".to_string());
        let provider = FixedProvider {
            response: r#"{"FullName": ""}"#.to_string(),
        };
        let result = suggest_fills(&fields, &profile, &provider).unwrap();
        assert!(result.is_empty());
    }

    /// Real end-to-end pass against a local Ollama model — confirms the
    /// prompt shape actually elicits usable JSON from a real (non-mocked)
    /// LLM, not just that our parser handles hand-written fixtures. Skips
    /// (doesn't fail) when Ollama is unavailable.
    #[test]
    fn suggest_fills_works_against_a_real_local_model() {
        let fields = vec![text_field("FullName"), text_field("EmailAddress")];
        let mut profile = HashMap::new();
        profile.insert("full_name".to_string(), "Jane Doe".to_string());
        profile.insert("email".to_string(), "jane@example.com".to_string());

        let provider = OllamaProvider::new("qwen3:8b");
        match suggest_fills(&fields, &profile, &provider) {
            Ok(suggestions) => {
                // Not asserting exact matches — model output varies — just
                // that the round-trip through a real model produces
                // well-formed, field-scoped suggestions.
                for s in &suggestions {
                    assert!(["FullName", "EmailAddress"].contains(&s.field_name.as_str()));
                    assert!(!s.value.is_empty());
                }
            }
            Err(e) => eprintln!("skipping: provider unavailable ({e})"),
        }
    }
}
